# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-19 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('org_info', models.TextField(verbose_name='机构介绍')),
                ('image', models.ImageField(max_length=200, upload_to='org/%y/%m', verbose_name='机构图片')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': '机构',
                'verbose_name': '机构',
            },
        ),
        migrations.CreateModel(
            name='OrgCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('city_info', models.CharField(max_length=50, verbose_name='城市信息')),
            ],
            options={
                'verbose_name_plural': '城市',
                'verbose_name': '城市',
            },
        ),
        migrations.AddField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrgCity', verbose_name='机构地址'),
        ),
    ]
