# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-25 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180123_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='teacher/%y/%m', verbose_name='教师头像'),
        ),
    ]
