# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='click',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
