# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('primary', '初级'), ('mid', '中级'), ('highlevel', '高级')], max_length=20, verbose_name='难度等级'),
        ),
    ]
