# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-19 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=30, verbose_name='图片名字')),
                ('image', models.ImageField(max_length=200, upload_to='carousel/%y/%m', verbose_name='轮播图')),
                ('urls', models.URLField(verbose_name='图片地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序控制')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myemail', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('send_type', models.CharField(choices=[('registered', '注册验证码'), ('forget', '忘记验证码')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': '邮箱验证码',
                'verbose_name': '邮箱验证码',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='myemail',
        ),
    ]
