# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180121_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='send_type',
            field=models.CharField(choices=[('register', '注册验证码'), ('forget', '忘记验证码'), ('update', '修改邮箱')], max_length=10),
        ),
    ]
